services:
  web:
    build: .
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000 #python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./deploy_build:/var/www/
    #depends_on:
    #  - web
